<?php
    /**
     * Phyneapple!
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@phyneapple.com so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\Phyneapple
     * @copyright Copyright (c) 2013 Phyneapple! (http://www.phyneapple.com/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $images \PHY\Model\Image\Collection
     */
?>
<?php $tag = $this->tag() ?>
<?php $helper = $tag->helper() ?>
<?= $this->child('message') ?>
<script type="text/javascript">
    /* <![CDATA[ */
    window.onload = function() {
        !function($) {
            $.ajaxDispatcher('sorter', function(event) {
                event.type = $.ajaxDispatcher('default');
                var tr = $(event.caller.caller).parent().parent();
                event.callback = function(response) {
                    if (response.direction === 'up') {
                        tr.insertBefore(tr.prev());
                    } else {
                        tr.insertAfter(tr.next());
                    }
                    return false;
                };
                $('body').trigger(event);
            });
        }(jQuery);
    };
    /* ]]> */
</script>
<table class="table table-striped" id="images">
    <colgroup>
        <col width="5%"/>
        <col width="5%"/>
        <col/>
        <col width="5%"/>
        <col width="5%"/>
        <col width="5%"/>
        <col width="2.5%"/>
        <col width="10%"/>
    </colgroup>
    <thead>
    <tr>
        <th>Sort</th>
        <th>Thumbnail</th>
        <th>Title</th>
        <th colspan="5"></th>
    </tr>
    </thead>
    <tbody>
    <?php if (count($images)): ?>
        <?php foreach ($images as $row): ?>
            <tr class="image-<?= $row->image->id() ?>">
                <td class="galleryLinked-<?= $row->linked->sort ?>-sort"><?= $row->sort ?></td>
                <td class="image-<?= $row->image->id() ?>-name"><?php if ($row->image->file): ?><img
                        src="<?= $this->clean($row->image->thumbnail
                            ?: $row->image->file); ?>"
                        alt="<?= $this->clean($row->image->alt) ?>" style="height:20px; width:20px;"/><?php endif ?>
                </td>
                <td class="image-<?= $row->image->id() ?>-title"><?= $this->clean($row->image->title); ?></td>
                <td class="action"><?= $tag->helper()
                        ->url('Edit', '/admin/image/id/' . $row->image->id() . '/gallery_id/' . $item->id()) ?></td>
                <td class="action">
                    <?= $helper->url('Remove', '/admin/image/id/' . $row->image->id() . '/gallery_id/' . $item->id() . '/remove', [
                        'class' => 'ajax',
                        'data' => [
                            'method' => 'delete',
                            'confirm' => 'remove',
                            'message' => 'Are you sure you want to remove ' . $this->clean($row->image->title) . ' from this gallery?',
                            'type' => 'confirm',
                            'element' => '.image-' . $row->image->id()
                        ]
                    ]) ?>
                </td>
                <td class="action"><?= $helper->url($tag->span->class([
                        'glyphicon',
                        'glyphicon-arrow-up'
                    ]), '/admin/galleryImageSort/gallery_id/' . $item->id() . '/image_id/' . $row->image->id() . '/sort/up', [
                        'class' => 'ajax',
                        'data' => [
                            'method' => 'post',
                            'type' => 'sorter'
                        ]
                    ]) ?></td>
                <td class="action"><?= $helper->url($tag->span->class([
                        'glyphicon',
                        'glyphicon-arrow-down'
                    ]), '/admin/galleryImageSort/gallery_id/' . $item->id() . '/image_id/' . $row->image->id() . '/sort/down', [
                        'class' => 'ajax',
                        'data' => [
                            'method' => 'post',
                            'type' => 'sorter'
                        ]
                    ]) ?></td>
                <td class="action form-control">
                    <label class="sr-only" for="galleryLinked-<?= $row->linked->id() ?>">Jump:</label>
                    <input class="form-control jump galleryLinked-<?= $row->linked->sort ?>-sort"
                           id="galleryLinked-<?= $row->linked->id() ?>" name="jump"
                           type="number"
                           value="<?= $row->linked->sort ?>"/>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="4">No images have been added yet. <a
                    href="<?= $this->url('admin/image/id/0?gallery_id=' . $item->id()) ?>"
                    class="btn btn-sm btn-primary">Add</a>
            </td>
        </tr>
    <?php endif ?>
    </tbody>
</table>
<?= $this->child('pagination') ?>
<form action="<?= $this->url('admin/galleryJump') ?>" id="jump-form" method="POST"></form>
<script type="text/javascript">
    require(['jquery'], function($) {
        var ENTER_KEY = 13;
        var makeInput = function(key, value) {
            var input = document.createElement('INPUT');
            input.name = key;
            input.id = key;
            input.type = 'hidden';
            input.value = value;
            return input;
        };
        $(function() {
            $('#images').on('keypress', '.jump', function(event) {
                console.log(event);
                if (event.keyCode !== ENTER_KEY && event.which !== ENTER_KEY) {
                    return true;
                }
                var item = $(this);
                var jumpForm = $('#jump-form')[0];
                jumpForm.appendChild(makeInput('jump', item.val()));
                jumpForm.appendChild(makeInput('gallery_id', item.data('image_id')));
                jumpForm.submit();
            });
        });
    });
</script>
