<?php /** @var $image \PHY\Model\Image */ ?>
<?= $this->child('jumbotron') ?>
<?php foreach ($galleries as $gallery): ?>
    <?php $images = $galleryImages($gallery->id()); ?>
    <?php if ($count = count($images)): ?>
        <div class="row row-bg">
            <div class="col-sm-9">
                <div class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="item active">
                            <div class="row thumbnail-gallery">
                                <?php for ($i = 0; $i < $count; ++$i): ?>
                                    <?php if ($i > 11):
                                        break;
                                    endif ?>
                                    <?php $image = $images[$i] ?>
                                    <div class="col-xs-4 col-sm-2">
                                        <div class="thumbnail">
                                            <a href="<?= $this->clean($image->getImage()) ?>"
                                               data-toggle="lightbox" data-parent=".thumbnail-gallery"><img
                                                    src="<?= $this->clean($image->thumbnail) ?>" height="60"
                                                    alt="<?= $this->clean($image->title) ?>"/></a>
                                        </div>
                                    </div>
                                <?php endfor ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 hidden-xs">
                <div class="hover" data-gallery="<?= (int)$gallery->id() ?>" data-more="<?= $count > 12
                    ? 1
                    : 0 ?>" style="position:relative">
                    <img class="hover-img" src="<?= $this->url($gallery->url . '.jpg', 'image') ?>"
                         alt="<?= $this->clean($gallery->name) ?>"/>
                    <img class="hover-up" src="<?= $this->url('hover-up.png', 'image') ?>"/>
                    <img class="hover-down" src="<?= $this->url('hover-down.png', 'image') ?>"/>
                </div>
            </div>
            <ul class="pager visible-xs">
                <li><a href="#" class="btn btn-danger prev">&laquo; Previous</a></li>
                <li><a href="#" class="btn btn-danger next">Next &raquo;</a>>Next</a></li>
            </ul>
        </div>
    <?php endif ?>
<?php endforeach ?>
<div class="hidden-xs hidden-sm hidden-md visible-lg"><img
        src="<?= $this->url('footer.png', 'image') ?>"
        alt=""/></div>
<script>
    !function($) {
        var running = false;
        var loc = function(element, event) {
            var $element = $(element);
            var offsetTop = event.pageY - element.offsetTop - $element.offset().top;
            var offsetLeft = event.pageX - element.offsetLeft - $element.offset().left;
            var half = $element.height() / 2;
            if (offsetLeft < 148) {
                return false;
            }
            if (offsetTop > half) {
                return {
                    off: 'up',
                    on: 'down'
                };
            }
            return {
                off: 'down',
                on: 'up'
            };
        };
        $('.hover').each(function() {
            var less = false;
            var element = $(this);
            var completed = false;
            var elementHolder = element.parent().parent();
            var elementCarousel = $('.carousel', elementHolder);
            var started = false;
            var $element = $(this);

            var galleryId = $element.data('gallery');
            var getMore = function() {
                if (completed) {
                    elementCarousel.carousel('next').carousel('pause');
                    started = false;
                    return;
                }
                less = true;
                running = true;
                var caller = element.data('caller');
                var more = element.data('more');
                if (!more) {
                    completed = true;
                    started = false;
                    return;
                }
                caller = parseInt(caller || 0);
                ++caller;
                $.post('<?= $this->url('more') ?>', {galleryId: galleryId, _caller: caller})
                    .done(function(res) {
                        running = false;
                        element.data('caller', caller);
                        if (!res.content) {
                            completed = true;
                            started = false;
                            return;
                        }
                        $('.carousel-inner', elementCarousel).append(res.content);
                        if (!res.more) {
                            completed = true;
                        }
                        elementCarousel.carousel('next').carousel('pause');
                        started = false;
                    })
                    .fail(function(res) {
                        running = false;
                        started = false;
                    });
            };

            $element.on('mouseenter mousemove', '.hover-img', function(e) {
                var locations = loc(this, e);
                if (!locations) {
                    return false;
                }
                $('.hover-' + locations.on, $element).show();
                $('.hover-' + locations.off, $element).hide();
            }).on('mouseleave', '.hover-img', function(e) {
                $('.hover-up,.hover-down', $element).hide();
            }).on('click', '.hover-img', function(e) {
                var locations = loc(this, e);
                if (!locations) {
                    return false;
                }
                event.stopPropagation();
                if (started) {
                    return false;
                }
                started = true;
                if (locations.on === 'up') {
                    var run = function() {
                        if (!running) {
                            getMore();
                        } else {
                            setTimeout(run, 100);
                        }
                    };
                    run();
                    return false;
                }
                if (less) {
                    elementCarousel.carousel('prev').carousel('pause');
                    started = false;
                }
                return false;
            });
            $(elementHolder).on('click', '.prev', function() {
                if (less) {
                    elementCarousel.carousel('prev').carousel('pause');
                    started = false;
                }
                return false;
            });
            $(elementHolder).on('click', '.next', function() {
                event.stopPropagation();
                if (started) {
                    return false;
                }
                var run = function() {
                    if (!running) {
                        getMore();
                    } else {
                        setTimeout(run, 100);
                    }
                };
                run();
                return false;
            });
        });
        $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
            event.preventDefault();
            $(this).ekkoLightbox();
        });
        var carousel = $('#carousel-featured');
        $('img', carousel).first().load(function() {
            carousel.height(this.height);
        });
    }(jQuery);
</script>
