<div class="page-header">
    <h1>Contact</h1>
</div>
<div class="row">
    <div class="col-sm-6">
        <form action="<?= $this->url('contact') ?>" method="post" role="form">
            <?= $this->child('contact/message') ?>
            <div class="form-group">
                <label for="contact-name" class="control-label">Your Name</label>
                <input id="contact-name" class="form-control" name="email[Name]" type="name"/>
            </div>
            <div class="form-group">
                <label for="contact-email" class="control-label">Your Email</label>
                <input id="contact-email" class="form-control" name="email[Email]" type="email"/>
            </div>
            <div class="form-group">
                <label for="contact-message" class="control-label">Message</label>
                <textarea id="contact-message" class="form-control" name="email[Message]" rows="5" cols="30"></textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-danger">Send</button>
            </div>
        </form>
    </div>
</div>