<?php
    /**
     * Phyneapple!
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@phyneapple.com so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\Phyneapple
     * @copyright Copyright (c) 2013 Phyneapple! (http://www.phyneapple.com/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $collection \PHY\Model\Gallery\Collection
     */
?>
<?php $tag = $this->tag() ?>
<?php $helper = $tag->helper() ?>
<?= $this->child('message') ?>
    <script type="text/javascript">
        /* <![CDATA[ */
        window.onload = function() {
            !function($) {
                $.ajaxDispatcher('sorter', function(event) {
                    event.type = $.ajaxDispatcher('default');
                    var tr = $(event.caller.caller).parent().parent();
                    event.callback = function(response) {
                        if (response.direction === 'up') {
                            tr.insertBefore(tr.prev());
                        } else {
                            tr.insertAfter(tr.next());
                        }
                        return false;
                    };
                    $('body').trigger(event);
                });
            }(jQuery);
        };
        /* ]]> */
    </script>
    <table class="table table-striped">
        <colgroup>
            <col/>
            <col/>
            <col width="5%"/>
            <col width="5%"/>
            <col width="5%"/>
            <col width="2.5%"/>
            <col width="2.5%"/>
        </colgroup>
        <thead>
        <tr>
            <th>Slug</th>
            <th>Title</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php if (count($collection)): ?>
            <?php foreach ($collection as $item): ?>
                <tr class="gallery-<?= $item->id() ?>">
                    <td class="gallery-<?= $item->id() ?>-url"><?= $this->clean($item->url); ?></td>
                    <td class="gallery-<?= $item->id() ?>-name"><?= $this->clean($item->name); ?></td>
                    <td class="action"><?= $tag->helper()->url('Edit', '/admin/gallery/id/' . $item->id()) ?></td>
                    <td class="action"><?= $tag->helper()
                            ->url('Images', '/admin/galleryImage/id/' . $item->id()) ?></td>
                    <td class="action">
                        <?=
                            $helper->url('Delete', '/admin/gallery/id/' . $item->id(), [
                                'class' => 'ajax',
                                'data' => [
                                    'method' => 'delete',
                                    'confirm' => 'remove',
                                    'message' => 'Are you sure you want to delete ' . $this->clean($item->title) . '?',
                                    'type' => 'confirm',
                                    'element' => '.gallery-' . $item->id()
                                ]
                            ]) ?>
                    </td>
                    <td><?= $helper->url($tag->span->class([
                            'glyphicon',
                            'glyphicon-arrow-up'
                        ]), '/admin/gallerySort/id/' . $item->id() . '/sort/up', [
                            'class' => 'ajax',
                            'data' => [
                                'method' => 'post',
                                'type' => 'sorter'
                            ]
                        ]) ?></td>
                    <td><?= $helper->url($tag->span->class([
                            'glyphicon',
                            'glyphicon-arrow-down'
                        ]), '/admin/gallerySort/id/' . $item->id() . '/sort/down', [
                            'class' => 'ajax',
                            'data' => [
                                'method' => 'post',
                                'type' => 'sorter'
                            ]
                        ]) ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="4">No galleries have been added yet. <a
                        href="<?= $this->url('admin/gallery/id/0') ?>"
                        class="btn btn-sm btn-primary">Add</a>
                </td>
            </tr>
        <?php endif ?>
        </tbody>
    </table>
<?= $this->child('pagination') ?>