<?php
    /**
     * Phyneapple!
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@phyneapple.com so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\Phyneapple
     * @copyright Copyright (c) 2013 Phyneapple! (http://www.phyneapple.com/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $item \PHY\Model\Gallery
     */
?>
<form action="<?= $_SERVER['REQUEST_URI'] ?>" class="form" method="post">
    <?= $this->getXsrfIdField() ?>
    <?= $this->child('message') ?>
    <div class="row">
        <div class="col-sm-6 col-lg-6">
            <div class="form-group">
                <label for="gallery-title" class="control-label">Name</label>
                <input id="gallery-title" class="form-control" name="gallery[name]" type="text"
                       value="<?= $this->clean($item->name) ?>"/>
            </div>
        </div>
        <div class="col-sm-6 col-lg-6">
            <div class="form-group">
                <label for="gallery-url" class="control-label">Slug</label>
                <input id="gallery-url" class="form-control" name="gallery[url]" type="text"
                       value="<?= $this->clean($item->url) ?>"/>
            </div>
        </div>
    </div>
    <hr/>
    <div class="form-group">
        <button class="btn btn-primary">Save</button>
    </div>
</form>