<div class="modal fade" id="jumbotron-register" tabindex="-1" role="dialog" aria-labelledby="jumbotron-register-label" aria-hidden="true">
    <div class="modal-dialog">
        <form class="form" method="post">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="jumbotron-register-label">Register For Free!</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="contact-name" class="control-label">Your Name</label>
                        <input id="contact-name" class="form-control" name="email[name]" type="name"/>
                    </div>
                    <div class="form-group">
                        <label for="contact-email" class="control-label">Your Email</label>
                        <input id="contact-email" class="form-control" name="email[email]" type="email"/>
                    </div>
                    <div class="form-group">
                        <label for="contact-message" class="control-label">Message</label>
                        <textarea id="contact-message" class="form-control" name="email[message]" rows="5" cols="30"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-danger">Register!</button>
                </div>
            </div>
        </form>
    </div>
</div>